## Tensorflow basic operations

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.constant(2.3)
y = tf.constant(3.0)
z = tf.constant(4.0)

In [3]:
print(tf.math.add(x, z))

tf.Tensor(6.3, shape=(), dtype=float32)


In [4]:
print(tf.math.multiply(x, y))

tf.Tensor(6.8999996, shape=(), dtype=float32)


In [5]:
array = tf.constant([[1,2,3,4], [-1,-2,-3,-4], [5,6,7,8]])
tf.math.segment_sum(array, tf.constant([0, 0, 1]))

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [5, 6, 7, 8]], dtype=int32)>

In [6]:
array = tf.constant([[1,2,3,4], [-1,-2,-3,-4], [5,6,7,8]])
tf.math.unsorted_segment_sum(array, tf.constant([0, 1, 0]), num_segments=2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 6,  8, 10, 12],
       [-1, -2, -3, -4]], dtype=int32)>

In [7]:
tf.add(x, y)

<tf.Tensor: shape=(), dtype=float32, numpy=5.3>

In [8]:
tf.add([1, 2], [3, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>

In [9]:
tf.square([6, 2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([36,  4], dtype=int32)>

In [10]:
tf.reduce_sum([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [11]:
total = tf.square([25, 30]) + tf.square([30, 5])

In [12]:
total

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1525,  925], dtype=int32)>

In [13]:
tf.matmul([[1]], [[2, 3]])

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[2, 3]], dtype=int32)>

In [14]:
tf.multiply(np.ones([3, 3]), 42)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[42., 42., 42.],
       [42., 42., 42.],
       [42., 42., 42.]])>

In [16]:
tensor.numpy()

NameError: name 'tensor' is not defined

In [ ]:
tf.random.uniform([3, 3])

## Check tensorflow GPU

In [ ]:
tf.config.list_physical_devices("CPU")

In [ ]:
x.device.endswith('GPU:0')

In [ ]:
with tf.device("CPU:0"):
    x = tf.random.uniform([1000, 1000])
    assert x.device.endswith("CPU:0")